#  ╔═╗╦  ╔═╗╔═╗╦═╗╦╔╦╗╔╦╗╦ ╦  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠═╣║  ╠═╣║  ╠╦╝║ ║  ║ ╚╦╝  ║  ║ ║║║║╠╣ ║║ ╦	- Config by z0mbi3
#  ╩ ╩╩═╝╩ ╩╚═╝╩╚═╩ ╩  ╩  ╩   ╚═╝╚═╝╝╚╝╚  ╩╚═╝	- https://github.com/gh0stzk/dotfiles
#  General configuration

import:
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/fonts.yml
  
window:
  padding:
    x: 15
    y: 15

  decorations: none

  opacity: 1.0
  dynamic_title: true

  history: 10000
  multiplier: 3

selection:
  save_to_clipboard: false

cursor:
  style:
    shape: Block
    blinking: On
    
  unfocused_hollow: false 
  blink_interval: 550

live_config_reload: true
