#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
#	gh0stzk - https://github.com/gh0stzk/dotfiles

[general]
import = [
"themes/emilia.toml",
"fonts.toml",
]

live_config_reload = true

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
padding = { x = 15, y = 15 }
dynamic_padding = true
resize_increments = true

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }
